services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: flask
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pflask"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge