apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: loginapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: loginapp-web:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: flaskapp
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: flask-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: loginapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: flaskapp
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

